/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_spark_ml_clustering_KMeansDALImpl */

#ifndef _Included_org_apache_spark_ml_clustering_KMeansDALImpl
#define _Included_org_apache_spark_ml_clustering_KMeansDALImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_spark_ml_clustering_KMeansDALImpl
 * Method:    cKMeansDALCompute
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_clustering_KMeansDALImpl_cKMeansDALCompute
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_apache_spark_ml_clustering_KMeansDALImpl
 * Method:    cKMeansDALComputeWithInitCenters
 * Signature: (JJIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_spark_ml_clustering_KMeansDALImpl_cKMeansDALComputeWithInitCenters
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
